### ISSUE TITLE
Grafana Webhook not working

### ISSUE THREAD

**Issue by MartinDinev97** [alerta/alerta#1956] opened 2024-05-11 00:01 UTC
**Issue Summary**
Grafana webhook is not working, we're using the Prometheus one to handle the Grafana payload.

**Environment**
- OS: Linux
- Deployment: k8s pod 
- For self-hosted, WSGI environment: uwsgi
- Database: Postgres

- Server config:
  Auth enabled? Yes
  Auth provider? Basic
  Customer views? No

I can provide a sample of the Grafana v10.4.1 payload if required but I believe people already posted some in other threads. Is there something that can be done or someone with knowledge to fix it ?

Thank you in advance!

**Comment by hyberdk** [comment] 2024-06-12 08:09
To my knowledge the Grafana alerting implementation has changed many times over the last few years..  Im closing this as a duplicate of #1676 there is no reason to have multiple tickets open for the same issue..

I suggest that you add your sample json to that issue.. also please include how you have configured grafana for alerting

**Closed by hyberdk** 2024-06-12 08:09 UTC
