### ISSUE TITLE
GitLab Auth and Customer association broken

### ISSUE THREAD

**Issue by jurgenhaas** [alerta/alerta#1179] opened 2020-04-07 08:30 UTC
**Issue Summary**

Looks like #828 is broken again. The setup for GitLab is the same as described there and I hope it's OK top not repeat all the config in this issue here again.

The user is member of 5 relevant groups:

![Screenshot from 2020-04-07 10-20-08](https://user-images.githubusercontent.com/1475675/78647272-9fe42280-78ba-11ea-9716-1434c6a2621c.png)

But in Alerta they only see heartbeats of one customer:

![Screenshot from 2020-04-07 10-20-45](https://user-images.githubusercontent.com/1475675/78647307-aecad500-78ba-11ea-8ac5-57a6b19407f3.png)

It seems like the GitLab groups which is NOT a sub-group gets recognized but not the others.

**Comment by satterly** [comment] 2020-04-11 15:21
Works for me ...

<img width="429" alt="Screenshot 2020-04-11 at 17 00 19" src="https://user-images.githubusercontent.com/615057/79047733-bc64bf80-7c18-11ea-874c-c28e09f8829c.png">

<img width="379" alt="Screenshot 2020-04-11 at 17 00 34" src="https://user-images.githubusercontent.com/615057/79047735-c1297380-7c18-11ea-9cd5-8d7c7063d960.png">

<img width="651" alt="Screenshot 2020-04-11 at 17 02 16" src="https://user-images.githubusercontent.com/615057/79047736-c686be00-7c18-11ea-97c7-f005618982b3.png">

<img width="1235" alt="Screenshot 2020-04-11 at 17 18 23" src="https://user-images.githubusercontent.com/615057/79047739-cbe40880-7c18-11ea-90c3-4771b7b9a9a7.png">


<img width="578" alt="Screenshot 2020-04-11 at 17 18 49" src="https://user-images.githubusercontent.com/615057/79047704-9ccd9700-7c18-11ea-9cb6-476539eb7062.png">

You're going to have to show me the customer<->group assignments as that is what is relevant here.

**Comment by jurgenhaas** [comment] 2020-04-11 15:46
Here is the lookup table for customers:

![Screenshot from 2020-04-11 17-43-39](https://user-images.githubusercontent.com/1475675/79048270-3c405900-7c1c-11ea-9c9a-7642c0df6c57.png)

So that user above should be assigned to the customers arocom, gentner and zehnder, but he only gets the first one and not the others.

**Comment by satterly** [comment] 2020-04-11 19:14
Don't the lookups need to be `ansible-inventories/hosts/gentenr` etc.

**Comment by jurgenhaas** [comment] 2020-04-12 07:37
That's similar to the discussion we've had about a year ago in #828 and something must have changed again, because up until recently it was sufficient to only have the lookups for the group name, even if it was a subgroup's name.

What's interesting, when I add the full name including namespace (e.g. `ansible-inventories/hosts/gentner`), the result then looks like this:

![Screenshot from 2020-04-12 09-35-04](https://user-images.githubusercontent.com/1475675/79063315-2cb72380-7ca1-11ea-9006-ccdabc36de04.png)

So it then recognizes the namespaced lookup **and** then plain one. That doesn't hurt, but it indicates there is an issue.

**Comment by satterly** [comment] 2020-11-03 21:33
I've tried everything and can't reproduce this error. Below is the customer lookups and the groups and customers assigned to a profile. LGTM.

Customer Lookups

<img width="693" alt="Screenshot 2020-11-03 at 22 31 23" src="https://user-images.githubusercontent.com/615057/98042840-89885000-1e24-11eb-9092-82c2f2306889.png">

User Profile

<img width="686" alt="Screenshot 2020-11-03 at 22 31 10" src="https://user-images.githubusercontent.com/615057/98042805-78d7da00-1e24-11eb-9fea-28d363fad041.png">

If you can reliably reproduce this error then I'll take another look. Thanks.

**Closed by satterly** 2020-11-03 21:33 UTC
Labels: worksforme
