### ISSUE TITLE
Problem with Alerta Web UI

### ISSUE THREAD

**Issue by surajpanda1582** [alerta/alerta#772] opened 2018-11-30 06:42 UTC
I have installed Alerta server and alerta web UI both on same windows server. Alerta server is running fine. When I am running the web UI the alerts are not displaying and I see the following message on the command console
/vendor/fonts/glyphicons-halflings-regular.eot? HTTP/1.1" 200 -
404, message File not found
/vendor/js/angular-route.min.js.map HTTP/1.1" 404 -
404, message File not found
404, message File not found
/vendor/js/angular.min.js.map HTTP/1.1" 404 -
/vendor/js/angular-resource.min.js.map HTTP/1.1" 404 -
404, message File not found
/vendor/js/angular-sanitize.min.js.map HTTP/1.1" 404 -
404, message File not found
/vendor/js/angular.min.js.map HTTP/1.1" 404 -
404, message File not found
/vendor/js/angular-route.min.js.map HTTP/1.1" 404 -
404, message File not found
/vendor/js/angular-resource.min.js.map HTTP/1.1" 404 -
404, message File not found
/vendor/js/angular-sanitize.min.js.map HTTP/1.1" 404 -
/config.json HTTP/1.1" 200 -
404, message File not found
 /config.js HTTP/1.1" 404 -

Below are the config files receives from API server 
{"actions":[],"alarm_model":{"name":"Alerta 6.5.0"},"audio":{"new":null},"auth_required":false,"client_id":null,"colors":{"highlight":"skyblue ","severity":{"cleared":"#00CC00","critical":"red","debug":"#9D006D","indeterminate":"lightblue","informational":"#00CC00","major":"orange","minor":"yellow","normal":"#00CC00","ok":"#00CC00","security":"blue","trace":"#7554BF","unknown":"silver","warning":"dodgerblue"},"text":"black"},"columns":["severity","status","lastReceiveTime","duplicateCount","customer","environment","service","resource","event","value","text"],"customer_views":false,"dates":{"longDate":"d/M/yyyy h:mm:ss.sss a","mediumDate":"EEE d MMM HH:mm","shortTime":"HH:mm"},"endpoint":"http://localhost:8080","github_url":"https://github.com","gitlab_url":"https://gitlab.com","keycloak_realm":null,"keycloak_url":null,"pingfederate_url":null,"provider":"basic","refresh_interval":5000,"severity":{"cleared":5,"critical":1,"debug":7,"indeterminate":5,"informational":6,"major":2,"minor":3,"normal":5,"ok":5,"security":0,"trace":8,"unknown":9,"warning":4},"signup_enabled":true,"site_logo_url":"","sort_by":"lastReceiveTime","tracking_id":null}

When I see in the internet explorer developer tool I can see the below error 
Syntax Error in File: controllers.js, Line: 91, Column: 53.

Can anyone please help me resolving this issue. I am not able to find any root cause. Thanks

**Comment by satterly** [comment] 2018-11-30 12:22
Duplicate of https://github.com/alerta/angular-alerta-webui/issues/183

**Closed by satterly** 2018-11-30 12:22 UTC
Labels: duplicate
