### ISSUE TITLE
alerta-web uwsgi crashes when opening heartbeat

### ISSUE THREAD

**Issue by Schueni1** [alerta/alerta#1733] opened 2022-07-21 11:23 UTC
**Issue Summary**
When opening the heartbeat page in the webinterface I get the error _missing authorization key_ and uwsgi crashes. 

**Environment**
- OS: Linux
- Deployment: Docker kubernetes

- Database: Postgres

- Server config:
  Auth enabled? Yes
  Auth provider? LDAP
  Customer views? Yes

- web UI version: 8.7.0
- CLI version: 8.7.0

```
2022-07-21 11:13:14,462 DEBG 'nginx' stdout output:
10.1.67.55 - - [21/Jul/2022:11:13:14 +0000] "GET /api/heartbeats HTTP/1.1" 401 153 "-" "python-requests/2.26.0" - 0.001 x_forwarded_for=- host=alerta-web d73768471a9aed1a89561bf3930b7c63 5157eded-8910-46e8-a9fe-f45917b54303

2022-07-21 11:13:14,462 DEBG 'heartbeats' stdout output:
Error: Missing authorization API Key or Bearer Token

2022-07-21 11:13:14,479 DEBG fd 6 closed, stopped monitoring <POutputDispatcher at 139980249819688 for <Subprocess at 139980249820840 with name heartbeats in state RUNNING> (stdout)>
2022-07-21 11:13:14,480 INFO exited: heartbeats (exit status 1; not expected)
2022-07-21 11:13:14,480 DEBG received SIGCLD indicating a child quit
2022-07-21 11:13:15,482 INFO spawned: 'heartbeats' with pid 2078
2022-07-21 11:13:16,484 INFO success: heartbeats entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-07-21 11:13:37,684 DEBG 'uwsgi' stdout output:
worker 1 lifetime reached, it was running for 31 second(s)
worker 2 lifetime reached, it was running for 31 second(s)
worker 3 lifetime reached, it was running for 31 second(s)
worker 4 lifetime reached, it was running for 31 second(s)
worker 5 lifetime reached, it was running for 31 second(s)

2022-07-21 11:13:38,687 DEBG 'uwsgi' stdout output:
Respawned uWSGI worker 1 (new pid: 2081)
```

**Comment by satterly** [comment] 2023-12-23 20:01
Closing due to insufficient information given to reproduce error in a test environment.

**Closed by satterly** 2023-12-23 20:01 UTC
