### ISSUE TITLE
The duplicate events  "service" does not update the question to consult

### ISSUE THREAD

**Issue by net592** [alerta/alerta#896] opened 2019-03-25 11:12 UTC
**Issue Summary**
The service does not update the question to consult。

the first time i post alert

```
"event": "system.cpu.load[percpu,avg1]",
"resource": "zbx124.se.net",
"environment": "Production",
"service": ["service_name_group1", "service_name_group2"]
```

When my service changes i post alert,

```
"event": "system.cpu.load[percpu,avg1]",
"resource": "zbx124.se.net",
"environment": "Production",
"service": ["service_name_group1", "service_name_group2", "service_name_group3"]
```

i get this alert Response is still.
`"service": ["service_name_group1", "service_name_group2"]`
I hope it's
`"service":  ["service_name_group1", "service_name_group2", "service_name_group3"]`

Because I am converting to service with zabbix hostgroup 
When my hostgroup changes or adjusts, I expect the alerta service field to update,
This will cause inconvenience,  duplicate events How to update fields
Maybe not. Thank you

**Comment by satterly** [comment] 2019-03-25 12:52
This is a duplicate of #892 which you posted 3 days ago. The answer is the same.

https://github.com/alerta/alerta/issues/892#issuecomment-475678738

**Closed by satterly** 2019-03-25 12:52 UTC

**Comment by satterly** [comment] 2019-04-24 19:29
See #953

**Comment by net592** [comment] 2019-04-25 02:13
Nice
Thank you very much
