### ISSUE TITLE
Blackout timerange check uses create time, not a current one

### ISSUE THREAD

**Issue by hasso** [alerta/alerta#1132] opened 2020-01-28 18:31 UTC
**Issue Summary**

The current code changes state of the alert to blackout only if a create time is in the range of blackout. That's not what users expect. They expect it to transition to blackout if blackout is active now.

**Environment**
- OS: Linux
- API version: 7.4.1
- Deployment: self-hosted
- For self-hosted, WSGI environment: nginx/uwsgi

- Database: [eg. MongoDB, Postgres]

- Server config:
  Auth enabled? Yes
  Auth provider? Basic
  Customer views? No
  (or provide the `/config` endpoint output)

- web UI version: any
- CLI version: any

**To Reproduce**
1. Create a blackout for a resource which already has open alert(s).
2. Alert(s) remain open regardless of an active blackout and received duplicates.

**Expected behavior**
I'd expect all affected alerts changing status to blackout regardless how old these are.

**Additional context**
We are using alertmanager as a main source of alerts an it's periodically refreshes alerts. All alerts have a timeout set.

**Comment by satterly** [comment] 2020-01-28 22:03
Sounds reasonable. However, for context, this was changed in #895 after an issue was reported in #891. I'll review those first.

**Comment by satterly** [comment] 2020-01-29 22:58
Having just spent a few hours on this I'm struggling to get it to do what you say it does.

It works as you want if you set `NOTIFICATION_BLACKOUT=True`. ie. it will accept the alert and set the status to `blackout` based on the actual time the alert was created (because it hasn't hit the database yet so can't know if it is a duplicate and if it had been created prior to the blackout period).

On the other hand, if `NOTIFICATION_BLACKOUT=False` (the default) Alerta will reject the alert with the message "Suppressed alert during blackout period" and any existing alerts currently in the console **will not have their status changed.**

You didn't include your `alertad.conf` so I can't know if you set ``NOTIFICATION_BLACKOUT` to `True` or left it as the default (`False`). Please let me know.

**Comment by hasso** [comment] 2020-01-30 08:44
Yes, NOTIFICATION_BLACKOUT is set to True. It really depends on where create_time data is taken from. As far as I can understand it:

1) Alert is firing for resource A somewhere in the past.
2) Some time later admin sets a blackout starting the current time.
3) Alerta is recieiving duplicate alert for resource A, takes a create_time which is set to a timestamp set in "1)" from alert (StartsAt field in the alertmanager data).
4) Compares this create_time with blackout range, decides it's not a blackout.

**Comment by satterly** [comment] 2020-01-30 12:04
Ok. So what would be the downside of matching a blackout against both the create time and the receive time? ie. if either match then it's a blackout.

**Comment by hasso** [comment] 2020-01-31 09:39
This would mean that alerts created during blackout, but still active after blackout end time wouldn't leave blackout status then.

**Comment by satterly** [comment] 2020-01-31 11:14
You're right. So what's the solution?

**Comment by sushovan23** [comment] 2020-02-24 19:07
I am facing the same issue described. Where I had earlier alert which fires every hour. So now I decided to blackout it but since creation time was before blackout start date it didnt blackout. 

I think checking OR condition for matching against both creation time and last received time would work well.

As for this statement:
```This would mean that alerts created during blackout, but still active after blackout end time wouldn't leave blackout status then.```

If blackout rule has now expired & alert has refired then the state should reflect back to correct as even though creation time was within blackout rule but now that rule has expired so state for the refired/repeat alert should be open again.

**Comment by sushovan23** [comment] 2020-02-24 19:32
Furthermore can you suggest a solution to blackout alerts which are already firing?
I edited my blackout rule with start time before create time of alert but next fire/repeat its still open and not blackout? @satterly

**Comment by satterly** [comment] 2020-02-25 00:02
I have an idea...

* if an alert is received within it's timeout period assume that it is not a resend and use create time to determine blackout status

*   if the alert is received after create_time + timeout, then assume it is a resend and use the receive time to determine blackout status

Thoughts?

**Comment by sushovan23** [comment] 2020-02-25 00:23
It will not work - 
We are currently setting the timeout to a larger value and repeat alerts are fired before timeout is reached. 
I think you can anyways determine if alert is repeat or not. If it’s repeat then check using last received time instead of first received time.

**Comment by satterly** [comment] 2020-02-25 00:27
I wish it was that easy however, the nature of a "blackout" is meant to be that the alert does not hit the database if it is received within a blackout period. And until the alert hits the database we can't know if it's a repeat and whether to use receive time or last receive time.

Perhaps I need to rethink that ...

**Comment by sushovan23** [comment] 2020-02-25 00:37
I see blackout as a suppression system. So even if something is alerting and it’s not going to fixed in quick manner then we put suppression rule / blackout rule till it can be rectified. 

So with previous version of 5.x I know it worked as described above. 

Can I ask why was it changed to creation time instead of last received time? I think you can do a OR condition between creation time / last received time. 
Then both options are covered . I think it can be a potential solution without any side effects.
So it will suppress -
Alerts sent with creation time within the blackout period — suppress 
If creation time is not within blackout period then do a second check to see if last received time within the blackout period — suppress 

If both fail then let it go through not suppressed

**Comment by sushovan23** [comment] 2020-02-25 01:40
How about just checking against Current received time? I did see a pull request about ability to suppress or send alerts in past for blackout rule. 

I had worked on suppression system based on rules : there I used to just check for the current received time vs the time range in the suppression rule and it worked great.

**Comment by satterly** [comment] 2020-02-25 10:14
After considering this issue and possible solutions for *a long time now*, I've decided that the blackout period works as intended. What is broken is the Prometheus Alertmanager webhook integration. It should not set the "create time" to the "start time" of the Alertmanager alarm but let create time be set to the time the alert was actually created (ie. "now"). This will mean alerts received by Alerta will be matched against the correct blackout period whether the alert was delayed or not. Comments?

**Comment by satterly** [comment] 2020-02-25 10:24
Reviewing the other webhooks I think the Stackdriver integration is flawed as well -- when it comes to blackout periods, that is.

**Comment by sushovan23** [comment] 2020-02-25 14:44
That would work. Plus we would still have history tab to get all info on since when alert is firing.

**Closed** 2020-02-25 15:06 UTC
Labels: bug, question, worksforme

**Comment by sushovan23** [comment] 2020-03-10 17:33
@satterly is this available in any release yet?

**Comment by satterly** [comment] 2020-03-10 19:42
@sushovan23 Just released as v7.4.5 https://github.com/alerta/alerta/releases/tag/v7.4.5
