### ISSUE TITLE
Ability to create a blackout from an existing alert in the WebUI 

### ISSUE THREAD

**Issue by dakotacody** [alerta/alerta#1617] opened 2021-11-16 23:20 UTC
**Is your feature request related to a problem? Please describe.**
Not a problem, just a suggested feature

**Describe the solution you'd like**
It would be nice if there was a button on an alert that could populate a blackout template in the WebUI.  The user could then add or delete any of the blackout criteria to make it broader or keep it narrowed down to the single alert. 

**Describe alternatives you've considered**
Creating Blackouts currently works this would just help prevent someone from accidentally blacking out more alerts than they intend by initially populating the blackout with a very specific scope of the alert it came from. 

**Additional context**

**Comment by satterly** [comment] 2021-11-22 15:05
Duplicate of alerta/alerta-webui#451

**Closed by satterly** 2021-11-22 15:05 UTC
