### ISSUE TITLE
Reoccurring blackouts - feature request

### ISSUE THREAD

**Issue by m4ce** [alerta/alerta#1413] opened 2020-12-08 15:19 UTC
I was thinking it could be a nice addition to be able to define reoccurring blackouts. At the moment, blackouts are fixed and have to be defined between two specific dates. However, it'd be also useful to say that a blackout can occur every weekend or first Monday of the month between certain times. I think it can be pretty arbitrary?

**Comment by satterly** [comment] 2020-12-08 17:01
This has been considered before and rejected as you need a "long-running" service where-as Alerta is just a wsgi app that is spawned to handle requests as they come in. Duplicate of #960

**Closed by satterly** 2020-12-08 17:01 UTC
