### ISSUE TITLE
Disappearing API Keys

### ISSUE THREAD

**Issue by arielbend** [alerta/alerta#402] opened 2017-10-16 08:36 UTC
Hi,

I'm experiencing an issue in which upon undefined times, the API Keys I've created [also the out-of-the-box API keys, titled "cron jobs", which I'm not sure what are they for (and why they are duplicated many times), because even w/o them the default expiry cron job works], are disappearing and I have to re-create them.

Is there any reason for this, or is it a bug?

Thanks!

**Comment by satterly** [comment] 2017-10-16 09:28
Hi @arielbend, this sounds like a bug. I guess you are using the Docker image? There is a known issue (at least known to me, that is) where the API key for cron jobs (ie. housekeeping) is recreated each time the container is restarted. This isn't great but not critical.

However, API keys going missing is new. Are you able to get a mongo console and query mongoDB directly to double check the API keys have actually been dropped from the database?
```
> db.keys.find().pretty()
```

**Comment by arielbend** [comment] 2017-10-16 14:10
Yes, I ran the command and in fact only those keys I've re-created show up there.
And yes, regarding the second issue I'm using a Docker image. I guess it's less important though than the main issue.
Can I help you somehow in trying to figure it out?

**Comment by satterly** [comment] 2017-10-16 16:18
So are you saying the keys you create are visible in the MongoDB console but not visible in the web UI or `alerta` CLI?

What version of alerta server, client and web UI are you using?

**Comment by arielbend** [comment] 2017-10-17 09:43
No. The keys that got deleted are not visible anywhere. Those keys that are now visible in the MongoDB console (and in the UI) are those that I have created after the old ones got deleted.

Versions:
Server: 4.10.1
Client: 4.10.0
How do I check for web UI version?

**Comment by satterly** [comment] 2017-10-17 19:21
I'm having trouble reproducing this issue. Can you share your server config file `alertad.conf` ? (you should hide any usernames, passwords, hostnames or IP addresses). Thanks.

**Comment by arielbend** [comment] 2017-10-18 07:49
There you go:
DEBUG = True
BASE_URL = '/api'
SECRET_KEY =XXX
OAUTH2_CLIENT_ID = XXX
OAUTH2_CLIENT_SECRET = XXX
PLUGINS = ['reject']
ALLOWED_ENVIRONMENTS=['X', 'Y']

By the way, maybe I should mention it, might be relevant.
I wanted to run a couple of instances of the server (in k8s), and ran into a problem that the housekeeping cron job was running in each instance, resulting in alerts being marked as expired multiple times, by several instances.
In order to solve that, I created another Docker image, based on the original one, just without the cron job.
So now I have a single instance **with** housekeeping running, and multiple instances **without**.
It seems to work fine, but don't know if it might be relevant to this issue.

**Comment by satterly** [comment] 2017-10-19 09:36
Hi @arielbend Thanks for the background info. That's good to know. Sounds like it might be better to remove the cron job from the base container and let people configure the housekeeping cron job separately? Or would it be better to make it a config option? enable/disable hk cron job?

**Comment by arielbend** [comment] 2017-10-19 11:04
It would definitely be better to remove it from the base container, and make it a config option.
Another thing that would be nice to have configurable is the allowed environments.
Currently I had to add this to the docker-entrypoint.sh:
`ALLOWED_ENVIRONMENTS=$(python -c "print('${ALLOWED_ENVIRONMENTS}'.split(','))")`

But we're off of the main issue :)

**Comment by satterly** [comment] 2017-10-19 11:27
I think I'm going to struggle to replicate this without using the same docker container as you are.

Can you run the following command to get the exact SHA256 digest for the alerta image you are running and I'll use it for my testing?

```
$ docker images --digests | grep alerta-web
alerta/alerta-web                                          latest              sha256:4c269045e3c8f623623366be73c7216e56d5f2a28b5577a31efb54a2c69d6bbf   6d26c1aa298e        11 days ago         740MB
```

**Comment by arielbend** [comment] 2017-10-19 12:34
I don't have a digest, I guess the image format is not v2, but I can paste the content of it helps.
Also, I've changed the entrypoint script as well, so I should probably paste it as well.
Let me know if it would help.

**Comment by satterly** [comment] 2017-11-14 23:25
I'm working on a new docker container that should hopefully address this problem so I'm going to close this issue.

**Closed by satterly** 2017-11-14 23:25 UTC
Labels: bug

**Comment by arielbend** [comment] 2017-11-15 06:26
Great! Out of curiosity, may I ask what was the issue?

**Comment by satterly** [comment] 2017-11-15 13:32
I'm still not entirely sure. Part of the problem is the entrypoint script was getting too complicated. Hopefully a simpler script will make diagnosing this issue, if it persists, easier.
