### ISSUE TITLE
Alerta don't use the correct user attribute to do a nested LDAP search

### ISSUE THREAD

**Issue by Theoooooo** [alerta/alerta#1515] opened 2021-05-06 13:24 UTC
**Issue Summary**
First of all, English is not my native language. Sorry for the eventual spelling mistake but i will try to be as precise as possible.

I'm struggling to write a working LDAP configuration, and the more i'm trying to found the issue, the weirder it gets.

**Environment**
- OS: CentOS 7
- API version: [eg. 6.8.1]
- Deployment: Self-hosted
- For self-hosted, WSGI environment: nginx/uwsgi

- Database: Postgres

- Server config:
  Auth enabled? Yes
  Auth provider? LDAP with LDAPS
  Customer views? Yes

- web UI version: Latest version from the Master branch
- CLI version: none, it's not working for me

**To Reproduce**
1. Create a LDAP configuration from the different exemples available from the repo but form the issues opened by the users as well
2. Enable the **DEBUG** mode inside the configuration for uwsgi and the LDAP service
3. Start your uwsgi service
4. Try to authenticate via your LDAP crendentials
5. According to the debug logs, the LDAP service is able to found every groupe i'm member of, but it's not using my username attribute to lookup if i'm present inside the groups defines in the **LDAP_ALLOWED_GROUP** option.

**Expected behavior**
I was expecting Alerta to use the correct user attribute to lookup inside the groups from my Active Directory

**Configuration file `alertad.conf`**
```
# ===
# GENERAL CONFIGURATION
# ===
DATABASE_URL = 'postgres://user:password@POSTGRES_IP:5432/alerta'
PLUGINS=['reject']
ALLOWED_ENVIRONMENTS=['Production', 'Development', 'Code']
# ===
# AUTHENTICATION CONFIGURATION
# ===
AUTH_REQUIRED = True
CUSTOMER_VIEWS = True
ADMIN_USERS = ['ldap_admin_user']
ADMIN_ROLES = ['Administrateur']
USER_DEFAULT_SCOPES = ['read','write:alerts']
SECRET_KEY = 'my_secret_key_lmao'
# ===
# LDAP CONFIGURATION
# ===
DEBUG = True
AUTH_PROVIDER = "ldap"
ALLOWED_EMAIL_DOMAINS = ['domain.com']
LDAP_URL = "ldaps://LDAP_IP:636"
LDAP_ALLOW_SELF_SIGNED_CERT = True
LDAP_TIMEOUT = 10
LDAP_BASEDN = "DC=my,DC=domain,DC=com"

LDAP_DOMAINS = {
        "cyres": "sAMAccountName=%s,OU=Internal,OU=Users,OU=Cyres,DC=ad,DC=cyres,DC=fr"
}

LDAP_BIND_USERNAME = "CN=Alerta_ServiceAccount,OU=Logs,OU=ServicesAccount,OU=MyOU,DC=my,DC=domain,DC=com"
LDAP_BIND_PASSWORD = "HelloThere"

LDAP_USER_BASEDN = "OU=MyOU,DC=my,DC=domain,DC=com"
LDAP_USER_FILTER = "(|(sAMAccountName={username})(objectClass=inetOrgPerson))"
LDAP_GROUP_NAME_ATTR = 'cn'
LDAP_USER_NAME_ATTR = 'sAMAccountName'

LDAP_GROUP_BASEDN = "OU=Privileges,OU=MyOU,DC=my,DC=domain,DC=com"

LDAP_GROUP_FILTER = "(&(member:1.2.840.113556.1.4.1941:={userdn}))"
LDAP_GROUP_NAME_ATTR = "dn"
LDAP_USER_MEMBER_ATTRIBUTE = "displayName"
ALLOWED_LDAP_GROUPS = [
        "CN=MyPrivileges_1,OU=Privileges,OU=MyOU,DC=my,DC=domain,DC=com",
        "CN=MyPrivileges_2,OU=Privileges,OU=MyOU,DC=my,DC=domain,DC=com"
]

LDAP_DEFAULT_DOMAIN = "my.domain.com"

LDAP_CONFIG = {
        "OPT_REFERRALS": 0,
        "OPT_PROTOCOL_VERSION": 3,
        "OPT_DEBUG_LEVEL": -1
}
```

**Screenshots**
There is a screenshot when i'm trying to authenticate myself from the Web UI :
![image](https://user-images.githubusercontent.com/33425208/117305179-cb02c200-ae7e-11eb-923d-e24ef3d1d338.png)

**Logs**
Many parts has been obfusced to hide sensitive informations.
My used is found properly inside the AD, the userdn is retreived properly as well and then the service tries to found my account inside the groups defined. But while doing my request, **it's using my email unstead of using my displayName !!!!!**.

Of course it will never found my user if it's looking and an emain inside my groups. I'm not using my email as a displayName for my users. 

And i didn't found any option to specify which attribute to user while doing the lookup inside the groups such as using the displayName to found myself inside these groups.

I've got a similar setup for my service Grafana and i don't have any issue whatsoever with this, so i assume there is something wrong with this setup. And these is like no documentation whatsoever about half of the option i'm using here. I had to search for pretty much two days to actually found [this issue](https://github.com/alerta/alerta/issues/1435) which used a properly setuped LDAP configuration.

But the main part are readable :
```
=> result:
(101,
 [('CN=MyGroup_1,OU=Privileges,OU=MyOU,DC=my,DC=domain,DC=com',
   {}),
  ('CN=MyGroup_2,OU=Privileges,OU=MyOU,DC=my,DC=domain,DC=com',
   {}),
  ('CN=MyGroup_3,OU=MyOU,DC=my,DC=domain,DC=com',
   {}),
  ('CN=MyGroup_4,OU=Privileges,OU=MyOU,DC=my,DC=domain,DC=com', {}),
  ('CN=MyGroup_5,OU=Privileges,OU=MyOU,DC=my,DC=domain,DC=com',
   {}),
  ('CN=MyGroup_6,OU=Privileges,OU=MyOU,DC=my,DC=domain,DC=com',
   {}),
  ('CN=MyGroup_7,OU=Privileges,OU=MyOU,DC=my,DC=domain,DC=com',
   {}),
  ('CN=MyGroup_8,OU=Privileges,OU=MyOU,DC=my,DC=domain,DC=com',
   {}),
  ('CN=MyGroup_9,OU=Privileges,OU=MyOU,DC=my,DC=domain,DC=com', {}),
  ('MyGroup_1,OU=Privileges,OU=MyOU,DC=my,DC=domain,DC=com', {}),
  ('CN=MyGroup_10,OU=Privileges,OU=MyOU,DC=my,DC=domain,DC=com',
   {}),
  ('CN=MyGroup_11,OU=Privileges,OU=MyOU,DC=my,DC=domain,DC=com',
   {}),
  ('CN=MyGroup_12,OU=Privileges,OU=MyOU,DC=my,DC=domain,DC=com',
   {}),
  ('CN=MyGroup_13,OU=Privileges,OU=MyOU,DC=my,DC=domain,DC=com',
   {})],
 5,
 [])
2021-05-06 15:14:12,564 alerta.app[25337]: [DEBUG] ****************************************

            UPDATE users
            SET last_login=NOW() at time zone 'utc'
            WHERE id='48086af4-459d-4bfb-9f6a-2279666e0ad8'

**************************************** request_id=b11213dd-7bf0-412b-84cc-b562f24e1ec8 ip=172.31.6.21
2021-05-06 15:14:12,566 alerta.app[25337]: [DEBUG] ****************************************
SELECT scopes FROM perms WHERE match='user'
**************************************** request_id=b11213dd-7bf0-412b-84cc-b562f24e1ec8 ip=172.31.6.21
2021-05-06 15:14:12,569 alerta.app[25337]: [DEBUG] ****************************************
SELECT scopes FROM perms WHERE match='CN=MyGroup_1,OU=Privileges,OU=MyOU,DC=my,DC=domain,DC=com'
**************************************** request_id=b11213dd-7bf0-412b-84cc-b562f24e1ec8 ip=172.31.6.21
2021-05-06 15:14:12,570 alerta.app[25337]: [DEBUG] ****************************************
SELECT scopes FROM perms WHERE match='CN=MyGroup_2,OU=Privileges,OU=MyOU,DC=my,DC=domain,DC=com'
**************************************** request_id=b11213dd-7bf0-412b-84cc-b562f24e1ec8 ip=172.31.6.21

There's 14 groups, i'm cutting it up early

...

```
And then there is this specific line :
```
2021-05-06 15:14:12,586 alerta.app[25337]: [DEBUG] ****************************************
SELECT customer FROM customers WHERE match='my_user_email@my.domain.com' LIMIT 50 OFFSET 0
**************************************** request_id=b11213dd-7bf0-412b-84cc-b562f24e1ec8 ip=172.31.6.21
```
I mean, **why does he looking for an email here**, that's not what i'm trying to do. I don't get it.

Even after this, if checking the user inside the web UI after disabling LDAP authentication, the username used when my user was created inside the postgres database is my email. There's an option to set the user Display Name inside the interface with `LDAP_USER_NAME_ATTR` but there is no choice to use another attribute to lookup inside the groups other than the email. 

Since there is not much documentation about it, i didn't found a solution to this issue.

And then after this, it's cycling through all the groups where i'm member of again without finding my user. The request end with a 403 HTML return code.

**Comment by satterly** [comment] 2021-05-09 14:56
What happens if you disable `CUSTOMER_VIEWS` ? ie. `CUSTOMER_VIEWS = False`

**Comment by satterly** [comment] 2021-05-15 09:17
This issue is blocked waiting on more information. The description or subsequent comments do not provide enough information to triage, investigate or resolve the issue. Please review the description against the [issue template](https://raw.githubusercontent.com/alerta/.github/master/.github/ISSUE_TEMPLATE/bug_report.md) and ensure all relevant information is included. If you do not know what is expected you can ask on [Slack](https://slack.alerta.dev).

**Comment by Theoooooo** [comment] 2021-05-18 07:10
Sorry, i'm currrently studying this week, i will be able to invest further more this issue next week. I'll be updating this issue when i will try to understand a bit more what is causing this.

**Comment by Shuu-Ri** [comment] 2021-05-19 04:14
Hi @satterly,

I encounter a similar issue as raised by @Theoooooo. My email is grabbed as a login username instead of the actual username which I registered as admin.

As for your question, I can log in with my actual username without any issue when CUSTOMER_VIEWS=False, The customer views seem to "identify" my email as another user.

**Comment by Theoooooo** [comment] 2021-05-24 08:44
> This issue is blocked waiting on more information. The description or subsequent comments do not provide enough information to triage, investigate or resolve the issue. Please review the description against the [issue template](https://raw.githubusercontent.com/alerta/.github/master/.github/ISSUE_TEMPLATE/bug_report.md) and ensure all relevant information is included. If you do not know what is expected you can ask on [Slack](https://slack.alerta.dev).

I can finally try to fix this issue.
So, with the option `CUSTOMER_VIEWS` set to `False` i can undeed log in properly without any issue.

**Comment by satterly** [comment] 2021-05-24 09:49
So the issue isn't with LDAP it's with how users are assigned to customers. And unfortunately you blacked out the user-specific information that is used to do a lookup so it makes it difficult to help you.

What you need to to is add either of those values to a customer lookup so that when that user logs in they get assigned a customer. If you enable Customer Views but do not have any customer lookups defined no-one will be able to login.

**Comment by Theoooooo** [comment] 2021-05-24 09:57
Can you tell me which information you need to try to help me out ? The documentation about the LDAP configuration isn't really clear and i'm getting lost around the different explainations of how to assign users properly as customers inside the WebUi ...

I'm specifically the system to not use the email as a lookup attribute for my users, but in this case it's using it.
I'm using a similar configuration for my service Grafana and the difference here is i can specify which attribute to use as a lookup attribute inside my groups. In this case, i'm using the `displayName` attribute because it's how my users are getting lookup in my groups

**Comment by satterly** [comment] 2021-05-24 10:03
Can you join Slack? https://slack.alerta.dev

**Comment by Theoooooo** [comment] 2021-05-24 10:15
> Can you join Slack? https://slack.alerta.dev

I joined and i pinged you inside the #help channel

**Closed** 2021-05-25 07:52 UTC
Labels: blocked, question
