### ISSUE TITLE
gitlab auth looks broken on 7.3.0

### ISSUE THREAD

**Issue by freeseacher** [alerta/alerta#1029] opened 2019-07-19 17:50 UTC
**Issue Summary**
Auth via gitlab returns "Error: User freeseacher is not authorized "

**Environment**
- OS: alpine 3.9
- API version: 7.3
- Deployment: self-hosted
- For self-hosted, WSGI environment: nginx/uwsgi

- Database:MongoDB

- Server config:
  Auth enabled? Yes
  Auth provider? Gitlab OpenID
  Customer views? No
config.json 
```
{
    "endpoint": "/api",
    "provider": "gitlab",
    "client_id": "d7ae5171fc22638289598e3a2e65082b9c42a5a29d01056d0e3bb26300f0c218",
    "gitlab_url": "https://code.getnoc.com",
    "colors": {
        "severity": {
            "fatal": "#000000",
            "critical": "#D8122A",
            "major": "#EA680F",
            "minor": "#FFBE1E",
            "warning": "#BA2222",
            "indeterminate": "#A6ACA8",
            "cleared": "#00AA5A",
            "normal": "#00AA5A",
            "ok": "#00AA5A",
            "informational": "#00A1BC",
            "debug": "#9D006D",
            "security": "#333333",
            "unknown": "#A6ACA8"
        },
        "text": "white",
        "highlight": "lightgray"
    },
    "severity": {
        "fatal": 0
    },
    "dates": {
        "shortTime": "shortTime",
        "mediumDate": "medium",
        "longDate": "EEEE, MMMM d, yyyy h:mm:ss.sss a (Z)"
    },
    "audio": {
        "new": "/audio/Bike Horn.mp3"
    },
    "refresh_interval": 30000
}
```

- web UI version: 7.3.0
- CLI version: 7.3.0

**To Reproduce**
1. gitlab config
![изображение](https://user-images.githubusercontent.com/289277/61554605-fb892a00-aa65-11e9-9f95-f296f9778211.png)
2. 
```
cat /etc/alertad.conf 
DEBUG = True
BASE_URL = '/api'
SECRET_KEY = "xxxxx"
OAUTH2_CLIENT_ID = 'd7ae5171fc22638289598e3a2e65082b9c42a5a29d01056d0e3bb26300f0c218'
OAUTH2_CLIENT_SECRET = 'xxxx'
API_KEY_EXPIRE_DAYS = 365
ADMIN_USERS=['freeseacher']
ALLOWED_ENVIRONMENTS=['production','development','infrastructure','Production','Development','Infrastructure']
ALLOWED_GITLAB_GROUPS = ['sova']
AUTH_PROVIDER = 'gitlab'
```
3.  cat /etc/nginx/conf.d/alerta.conf 
```

server {
    listen 80 default_server;
    listen [::]:80 default_server;

    access_log /dev/stdout;
    error_log /dev/stderr;

    client_max_body_size 50m;

    root /app;

    location /api {
        proxy_pass http://alerta:8080;
        proxy_read_timeout 600;
        gzip on;
        gzip_types text/css text/x-js;
        proxy_set_header Host $http_host;
        proxy_set_header X-Scheme $scheme;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
```
4. as far as i can see 
https://github.com/alerta/alerta/blob/0e442dcaa5df8391eded285857c09d203bb66413/alerta/auth/oidc.py#L135
roles here evaluated to "user"
user.domain to `[...,'sova', ...]`

gitlab  12.0.3

**Comment by satterly** [comment] 2019-07-25 07:34
I don't understand what the problem is here. Can you provide more info? Like what GitLab groups is the user actually in?

**Comment by freeseacher** [comment] 2019-07-25 21:15
The problem is that config does not work as expected. 
user actually in group sova and that group is required to login.

**Comment by satterly** [comment] 2019-07-25 21:18
You said the domain was `sova` not the group. To only allow certain domains use `ALLOWED_EMAIL_DOMAINS`.

**Comment by satterly** [comment] 2019-07-28 18:06
Was there a version in which in worked as you expected?

**Comment by freeseacher** [comment] 2019-07-28 19:59
yep. 6.8.3 was my previous version that guarantee to log me in.

**Comment by satterly** [comment] 2019-07-28 20:49
The logic for this was fixed in https://github.com/alerta/alerta/pull/1010 . I suspect you had it misconfigured before then and didn't realise. Please check your config again.

**Comment by vykulakov** [comment] 2019-08-06 12:18
I use GitLab OAuth with recent versions of Alerta Server and Alerta WEB UI and I don't have any problems with auth process (except it doesn't work in Firefox). My user is also admin and the configuration is very similar. I'm experimenting now with a local server, but soon I'll deploy upgraded Alerta on prod and may give you some information about auth there.

**Comment by satterly** [comment] 2019-08-10 22:00
Closing due to inactivity. If you believe this issue has been closed prematurely please provide more information to help progress the issue. If you do not know what is expected you can ask on [Gitter chat](https://gitter.im/alerta/chat).

**Closed by satterly** 2019-08-10 22:00 UTC
Labels: question
